### ISSUE TITLE
Single user cancelled, team remained in active billing

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4527] opened 2024-09-20 13:39 UTC
### Current Behavior

Stripe customer: https://dashboard.stripe.com/customers/cus_OhIGn3mthqVQbt 

This customer was on the Starter plan and paying for several months. The customer then deleted their user, leaving the team with zero users. The bug: the team continued on with billing active despite there being no users.

### Expected Behavior

A team with no users is no longer billed.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by knolleary** [comment] 2024-09-20 13:43
The user deleted their account - which should have been prevented as they are the only owner of a team. This is something we have test coverage of, so need to figure out how that happened.

Unfortunately, this was reported over a month after they deleted their account - just outside out log retention window.

**Comment by knolleary** [comment] 2024-09-20 13:54
Have verified there are no other teams in this state of FFC

```
select "Teams".id, "Teams".slug, count(*) FROM "Teams" JOIN "TeamMembers" ON ("TeamMembers"."TeamId" = "Teams".id) GROUP BY "Teams".id HAVING count(*) < 1;
```

**Comment by hardillb** [comment] 2024-09-20 13:59
Do we want to look at making logs retain for ~45 days so we should always have coverage for billing issues like this?

**Comment by knolleary** [comment] 2024-09-20 14:00
@hardillb already spoke to @ppawlowski to do just that

**Comment by knolleary** [comment] 2024-09-20 15:30
Hmm, something wrong with my query as I've just stumbled over a team with no members.

**Comment by knolleary** [comment] 2024-09-20 15:50
This is the right query to return a list of teams that have no members:

```
select "Teams".slug, count("TeamMembers".role) as cc FROM "Teams" LEFT OUTER JOIN "TeamMembers" ON ("TeamMembers"."TeamId" = "Teams".id) GROUP BY "Teams".id HAVING count("TeamMembers".role) = 0;
```

We currently have 13 such teams in the database

**Comment by knolleary** [comment] 2024-09-20 16:29
Have identified https://github.com/FlowFuse/flowfuse/pull/4354 as the root cause of this. Am reverting the change for the weekend. Will reapply on Monday with the necessary changes.

**Comment by knolleary** [comment] 2024-09-23 10:02
Fixed via https://github.com/FlowFuse/flowfuse/pull/4531

**Closed** 2024-09-23 12:16 UTC
Labels: bug, needs-triage
