### ISSUE TITLE
Team Invite Notification Unclear

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#3039] opened 2023-11-02 09:02 UTC
## Scope (Marian)

- Add an "Invitations" menu item to the User menu.
- It should link directly to the invitation screens.

## License
Starter Tier

### Current Behavior

Today when you have a pending team invite, this shows as icon in the top right, there is a total of **5 steps** to see and accept the request.

Additionally, rejecting a request is far too easy to do by accident.

<img width="304" alt="Screenshot 2023-11-02 at 09 59 14" src="https://github.com/FlowFuse/flowfuse/assets/507155/fc7ca6fc-740b-49f1-8e8a-df86113e892e">

<img width="405" alt="Screenshot 2023-11-02 at 09 59 17" src="https://github.com/FlowFuse/flowfuse/assets/507155/f38cae05-801a-4cd1-830a-fd1be4801a6e">

<img width="408" alt="Screenshot 2023-11-02 at 09 59 21" src="https://github.com/FlowFuse/flowfuse/assets/507155/29439e2c-f2ce-4306-80b6-2bbe7ac54141">

<img width="1496" alt="Screenshot 2023-11-02 at 09 59 29" src="https://github.com/FlowFuse/flowfuse/assets/507155/a1df13f7-07b5-4cff-94e4-b0ccc13de46b">

<img width="1471" alt="Screenshot 2023-11-02 at 09 59 34" src="https://github.com/FlowFuse/flowfuse/assets/507155/10f1cf29-6534-4455-a50d-0ff932f0ed06">

### Expected Behavior

We should surface this pending invitation much faster. Perhaps it arrives as a notification in a notifications section, that links straight to the invitation page. Additionally, accept/reject is hidden behind a meatball menu.

It should have a much clearer call to action, such as an accept/reject button group in the table row (See: https://github.com/FlowFuse/flowfuse/issues/3038). Ideally with a "are you sure" popup for reject as it's easy to do by accident.

### Steps To Reproduce

Invite a user to a team and watch them try to find the invitation. It's unclear.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment] 2023-11-08 12:31
hii @Pezmc I am willing to address this issue if no one else has already taken it on

**Comment by sumitshinde-84** [comment] 2023-11-17 11:33
Instead of routing users through multiple pages, we can create a separate notification page and an option in the header, similar to what GitHub has. This would allow users to easily jump directly to corresponding notification root pages. Additionally, having a dedicated notification page would be helpful for handling other notifications as well.

Another issue arises when a user wants to keep a invitation without accepting or rejecting it, resulting in the notification symbol persisting. To address this, we can introduce functionality on the notification page. When a notification is marked as read, we will store that information in the local storage. This way, the notification icon will not persist indefinitely 


![Screenshot (158)](https://github.com/FlowFuse/flowfuse/assets/110285294/90eb30e7-a432-4ca9-9ef0-f2fdbdbc337a)


![Screenshot (160)](https://github.com/FlowFuse/flowfuse/assets/110285294/11ac3ae8-75bd-4792-8a7e-d1f99d29f3b9)

**Comment by Pezmc** [comment] 2023-11-17 13:10
@Yndira-FlowForge @joepavitt Do you have UX input here? If @sumitshinde-84 is available to work on this issue I want to be sure what is implemented matches your expectations!

**Comment by joepavitt** [comment] 2023-11-17 13:20
From a UX perspective, I agree pretty much with everything @sumitshinde-84 has said. However, the complexities here actually exists in the underlying notifications infrastructure, in that, we don't have any. The (1) that appears in that corner is -very_ hardcoded to team invites, hence no direct "notification" to click on and link directly to the origin of that ping.

Ideally, we would have:

- Notifications Store/DB
    - with: Title/Description/Link/User
- Notifications Service (probably server-side?) that provides functionality to add and mark read/unread any notifications
- API with which to get notifications for a given user, and take the relevant mark read/unread functionality

The UI/UX here is the "easy" part

**Comment by joepavitt** [comment] 2023-11-17 13:26
> Additionally, accept/reject is hidden behind a meatball menu.

This is a very small, quick win task that can (and should) be done in isolation

**Comment by sumitshinde-84** [comment] 2023-11-17 14:03
Thank you, @joepavitt and @Pezmc, for reply. I completely agree with what @joepavitt said. I am ready to work on this task. Moreover, I suggest we separate the task of creating API endpoints by raising another issue.

**Comment by sumitshinde-84** [comment] 2023-11-18 07:07
> @Pezmc @Yndira-FlowForge Instead of routing users through multiple pages, we can create a separate notification page and an option in the header, similar to what GitHub has. This would allow users to easily jump directly to corresponding notification root pages. Additionally, having a dedicated notification page would be helpful for handling other notifications as well.
> 
> Another issue arises when a user wants to keep a invitation without accepting or rejecting it, resulting in the notification symbol persisting. To address this, we can introduce functionality on the notification page. When a notification is marked as read, we will store that information in the local storage. This way, the notification icon will not persist indefinitely
> 
> ![Screenshot (158)](https://user-images.githubusercontent.com/110285294/283779083-90eb30e7-a432-4ca9-9ef0-f2fdbdbc337a.png)
> 
> ![Screenshot (160)](https://user-images.githubusercontent.com/110285294/283780943-11ac3ae8-75bd-4792-8a7e-d1f99d29f3b9.png)

We can also display notifications for the latest updates, warnings about subscription expiry, Flowfuse announcements, etc., in that notification section

**Comment by joepavitt** [comment] 2023-11-21 09:37
> We can also display notifications for the latest updates, warnings about subscription expiry, Flowfuse announcements, etc., in that notification section

Agree entirely, but this is a much bigger scoped piece of work. Something that we should be doing sooner rather than later though (imo) - CC @MarianRaphael who does our scheduling

**Comment by MarianRaphael** [comment] 2023-11-28 15:05
Possible quick win: Team Invite's menu item in the "User Menu"

**Closed** 2024-01-09 13:53 UTC
Labels: area:frontend, size:M - 3

**Comment by Steve-Mcl** [comment] 2024-01-09 15:12
Issue found - not sure if it is related to this PR?  @joepavitt 

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/1dea023c-5765-4bac-8b0b-654d110a5dc5)

**Comment by Steve-Mcl** [comment] 2024-01-09 15:12
@Pezmc ^ (sorry i wrongly tagged Joe)

**Comment by Steve-Mcl** [comment] 2024-01-09 15:16
To be clear, I am referring to the UI glitch (misaligned table columns)

**Comment by Steve-Mcl** [comment] 2024-01-09 15:19
Other than prior mentioned UI glitch, working as expected.



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/fde3451e-532a-4909-bb57-f0732fc41cb6)

**Comment by joepavitt** [comment] 2024-01-09 15:26
> Issue found - not sure if it is related to this PR? @joepavitt

That'll be caused by me - it's adding a column for `row-actions` now too, although should only exist if that slot is used by any rows.

**Comment by Steve-Mcl** [comment] 2024-01-17 10:10
verified on staging
