### ISSUE TITLE
Failure to create assets folder results in unfriendly server 500 toast

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4467] opened 2024-09-09 08:40 UTC
Errors raised by attempting to generate a folder with an invalid name report back to the user via a toast however it is an unfriendly 500 error

![chrome_pNFRYsZGVt](https://github.com/user-attachments/assets/ab56f9c7-c6f2-427b-b50c-336a470f8423)

Can we check the error type and report a more friendly message like "Invalid folder name"?

_Originally posted by @Steve-Mcl in https://github.com/FlowFuse/flowfuse/issues/4422#issuecomment-2337492327_

**Comment by joepavitt** [comment] 2024-09-10 08:37
A 500 error here suggests server falls over too?

**Comment by cstns** [comment] 2024-09-18 08:48
this might be addressed in https://github.com/orgs/FlowFuse/projects/1/views/33?filterQuery=+-is%3Apr++frontend+-status%3Adone `frontend/src/components/file-browser/FileBrowser.vue:259` with a bit more info on the response message.

I'm having difficulties reproducing the error on linux though because I can throw any string at it an it will create the folder.

Any methods of forcing the api to fail would be appreciated.

**Closed** 2024-09-24 08:15 UTC
Labels: area:frontend, size:S - 2
