### ISSUE TITLE
Manage concurrent node-red editing

### ISSUE THREAD

**Issue by jmorris644** [FlowFuse/flowfuse#229] opened 2022-01-24 15:09 UTC
### Description

In working on node-red projects it has occurred quite often that one of the other developers has edited the flows while I have it open in a browser. I do get the warning that it has changed but by that time I too have made changes.

It seems to me that a method of allowing concurrent editing needs to be established.

**Comment by ZJvandeWeg** [comment] 2022-01-24 15:15
Partially related to: https://github.com/flowforge/flowforge/issues/218, as version control could/should allow for concurrent edits. Furthermore; how to design version control probably has this issue as requirement for the design.

**Comment by jmorris644** [comment] 2022-01-24 15:22
Yes, I did see #218 but was not sure it fit. I have no problem deleting this post if it is deemed that it does.

**Comment by ZJvandeWeg** [comment] 2022-01-24 15:23
@jmorris644 While related, it's not strictly the same. This issue is valid in it's own right, so let's keep it open. My comment was mostly aimed at cross-linking issues.

**Comment by hardillb** [comment] 2022-01-24 15:24
No need to delete it as it's always useful to help external requirements.

What will need to be looked at is how much of a feature like this is specific to FlowForge and how much would/should be implemented at the Node-RED level

**Comment by jmorris644** [comment] 2022-01-24 15:36
In #218 this "We currently use the app database to store flows - without any history. How we overlay history needs to be considered." is mentioned.

I find this very interesting. So in the current version of FF, the flows are being maintained in a db of some sort?

**Comment by hardillb** [comment] 2022-01-24 20:59
yes, because when deployed to docker/kubernetes there is no persistent filesystem storage.

Also using a database makes building things like:
-  a central change control system easier 
-  features around dev->test->production deployments 

(All things on the **potential** features list)

**Comment by joepavitt** [comment] 2024-07-17 10:29
Closing as duplicate of https://github.com/FlowFuse/node-red/issues/7

**Closed by joepavitt** 2024-07-17 10:29 UTC
Labels: feature-request, epic, scope:collaboration
