### ISSUE TITLE
Device "Developer Mode" tab shows editor mode disababled all the time

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#3499] opened 2024-02-19 15:32 UTC
### Current Behavior

The new automatic editor access is not reflected in the Device "Develper mode" tab

### Expected Behavior

Either remove the status display and the button, or have it refect current state

### Steps To Reproduce

- create device
- assign to applications
- open device page
- enable Developer mode
- view the "Developer mode" tab

### Environment

- FlowFuse version: 2.1.0
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: FF Cloud (and local)
- Browser:  All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment] 2024-02-19 15:39
https://app-eu1.hubspot.com/live-messages/26586079/inbox/3347819764?messageId=e5bc78b3906c4bbcb68f90f8f2827607

**Comment by Steve-Mcl** [comment] 2024-02-20 09:43
Duplicate of https://github.com/FlowFuse/flowfuse/issues/3473

**Closed** 2024-02-21 09:36 UTC
Labels: bug, size:M - 3, area:device
