### ISSUE TITLE
Bulk Device Actions

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#1695] opened 2023-02-10 16:50 UTC
### Description

Our current platform allows a user to manage devices as individual entities in a team/project.

For a team with multiple devices this can get unwieldy. This epic is to gather concepts on what UX improvements can be made around bulk device actions, and to then spin off the relevant stories.

(From a UX standpoint, there may be some common design elements to glean from this around bulk actions on any of our ui collections)

 - [ ] Assign multiple devices to a project
 - ...

**Comment by MarianRaphael** [comment] 2023-03-31 15:22
See also: https://github.com/orgs/flowforge/projects/3/views/9?pane=issue&itemId=17511732

**Comment by joepavitt** [comment] 2024-07-23 07:40
Closing as duplicate of https://github.com/FlowFuse/flowfuse/issues/2381

**Closed by joepavitt** 2024-07-23 07:40 UTC
Labels: epic, area:frontend, scope:device, area:device
