### ISSUE TITLE
Duplicate debug messages in Device Editor

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3751] opened 2024-04-19 12:46 UTC
### Current Behavior

Reported by a customer on FF Cloud. Over a period of time having the Device Editor connected, the debug messages start to get duplicated. Over extended periods of time, they start duplicating multiple times. The fix is to disable/enable the device editor.

---

Something in the proxy code is leading to duplicate messages over time. I suspect it will be tied to one of the websocket connections dropping and reconnecting. We'll need to recreate to see where the duplication occurs:

### Expected Behavior

No duplicate messages

### Steps To Reproduce

I haven't attempted to reproduce yet, however the customer says they see this quite often.

### Environment

FF Cloud at the time of raising this issue

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment] 2024-04-19 15:02
I'm trying to reproduce this locally, I've added a reverse proxy between the device agent and the forge app so I can break the connection while keeping the editor open by connecting directly to the forge app.

At the moment it looks like the device agent only tries to reconnect once as soon as the connection drops so need to work out how to get the proxy to drop the existing connection and accept the new one (restarting isn't quick enough to catch the reconnect)

**Comment by hardillb** [comment] 2024-04-22 12:27
I think I can now reproduce this locally, will continue dig

**Comment by hardillb** [comment] 2024-04-22 12:51
There appears to be a timing issue as restarting the connection doesn't always lead to multiple messages

**Comment by hardillb** [comment] 2024-04-26 09:27
Current status

I can reproduce this with a localfs build by placing a nginx proxy between the device agent and the forge app. This is done by using the following nginx config file and the docker nginx container

```
worker_processes 1;

events {
  worker_connections 1024;
}

error_log /dev/stderr;

http {

  server {
    listen 80;
    access_log /dev/stdout;

    root /var/www/html;

    location / {
	proxy_pass http://172.17.0.1:3000/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
    }
  }	
}
```

`172.17.0.1` is the IP address of the host machine on the default docker network on linux.

The docker container is started with:

```
docker run --rm -p 8080:80 -v `pwd`/ff.conf:/etc/nginx/nginx.conf:ro --name nginx-proxy nginx
```

with the ff.conf in the current directory.

I then edited the `device.yml` to use localhost:8080 rather than `localhost:3000`

Once the device agent is up and running and the editor is opened from the forge app you can restart nginx with

```
docker restart nginx-proxy
```

This may not always trigger the problem, but it's about 60% effective. If the nginx docker container doesn't restart quickly enough it may sometime lead to the device agent failing to reconnect and the device agent will need restarting and the editor closing and opening again.

My current theory is that the device agent is opening multiple websocket connections to the Node-RED instance and then forwarding the output of all the connections up the tunnel to the forge app and on to the open editor.

I didn't manage to  workout the right way to instrument the device agent to prove this yet.

**Closed** 2024-05-02 15:49 UTC
Labels: bug, needs-triage, size:M - 3, priority:high
